[build]
  base = "."
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PRODUCTION = "false"

# API redirects
[[redirects]]
  from = "/api/stripe/*"
  to = "/.netlify/functions/stripe-:splat"
  status = 200

[[redirects]]
  from = "/api/stripe"
  to = "/.netlify/functions/stripe-create-checkout-session"
  status = 200

# SPA redirect - this must be the LAST redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://js.stripe.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.stripe.com https://*.firebaseapp.com; frame-src https://js.stripe.com https://hooks.stripe.com https://*.stripe.com; form-action 'self' https://hooks.stripe.com; frame-ancestors 'self'"

# Function headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 